// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth').default>>>>
    }
    '/api/comments': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/comments').default>>>>
    }
    '/api/notes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notes').default>>>>
    }
    '/api/tasks': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks').default>>>>
    }
    '/api/users': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}